# Generated by Django 4.2.2 on 2024-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='email address', max_length=254, unique=True, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='улица')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
