# Generated by Django 4.2.2 on 2024-09-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Производитель'), (1, 'Дистрибьютор / Продавец'), (2, 'Продавец')])),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата добавления записи')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='контакт')),
                ('products', models.ManyToManyField(blank=True, null=True, to='products.product', verbose_name='продукция')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='поставщик', to='network.networknode', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'звено торговой сети',
                'verbose_name_plural': 'звенья торговой сети',
            },
        ),
    ]
